.PHONY: up down exec

up:
	docker-compose -f docker-compose.local.yml up

down:
	docker-compose -f docker-compose.local.yml down

exec:
	docker-compose -f docker-compose.local.yml exec <service-name> <command>

