FROM 988486663374.dkr.ecr.ap-northeast-1.amazonaws.com/base_python as base_python

#WORKDIR /app

# Add requirements file in the container
COPY requirements.txt ./requirements.txt
RUN pip install -r requirements.txt
# RUN pip wheel --no-cache-dir --no-deps --wheel-dir /app/wheels -r requirements.tx

# Add source code in the container
COPY main.py ./main.py

# Define container entry point (could also work with CMD python main.py)
ENTRYPOINT ["python", "main.py"]
