.PHONY: all clean

all: build

build:
	cargo build

run:
	cargo run

test:
	cargo test

bench:
	cargo bench

doc:
	cargo doc

clean:
	cargo clean

check:
	cargo check

update:
	cargo update

fix:
	cargo fix

clippy:
	cargo clippy

release:
	cargo build --release
