# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: outliers.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eoutliers.proto\x12\x02pb\x1a\x1fgoogle/protobuf/timestamp.proto\"O\n\x06Metric\x12(\n\x04time\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\x01\".\n\x0fOutliersRequest\x12\x1b\n\x07metrics\x18\x01 \x03(\x0b\x32\n.pb.Metric\"#\n\x10OutliersResponse\x12\x0f\n\x07indices\x18\x01 \x03(\x05\x32\x41\n\x08Outliers\x12\x35\n\x06\x44\x65tect\x12\x13.pb.OutliersRequest\x1a\x14.pb.OutliersResponse\"\x00\x42(Z&github.com/ardanlabs/python-go/grpc/pbb\x06proto3')



_METRIC = DESCRIPTOR.message_types_by_name['Metric']
_OUTLIERSREQUEST = DESCRIPTOR.message_types_by_name['OutliersRequest']
_OUTLIERSRESPONSE = DESCRIPTOR.message_types_by_name['OutliersResponse']
Metric = _reflection.GeneratedProtocolMessageType('Metric', (_message.Message,), {
  'DESCRIPTOR' : _METRIC,
  '__module__' : 'outliers_pb2'
  # @@protoc_insertion_point(class_scope:pb.Metric)
  })
_sym_db.RegisterMessage(Metric)

OutliersRequest = _reflection.GeneratedProtocolMessageType('OutliersRequest', (_message.Message,), {
  'DESCRIPTOR' : _OUTLIERSREQUEST,
  '__module__' : 'outliers_pb2'
  # @@protoc_insertion_point(class_scope:pb.OutliersRequest)
  })
_sym_db.RegisterMessage(OutliersRequest)

OutliersResponse = _reflection.GeneratedProtocolMessageType('OutliersResponse', (_message.Message,), {
  'DESCRIPTOR' : _OUTLIERSRESPONSE,
  '__module__' : 'outliers_pb2'
  # @@protoc_insertion_point(class_scope:pb.OutliersResponse)
  })
_sym_db.RegisterMessage(OutliersResponse)

_OUTLIERS = DESCRIPTOR.services_by_name['Outliers']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z&github.com/ardanlabs/python-go/grpc/pb'
  _METRIC._serialized_start=55
  _METRIC._serialized_end=134
  _OUTLIERSREQUEST._serialized_start=136
  _OUTLIERSREQUEST._serialized_end=182
  _OUTLIERSRESPONSE._serialized_start=184
  _OUTLIERSRESPONSE._serialized_end=219
  _OUTLIERS._serialized_start=221
  _OUTLIERS._serialized_end=286
# @@protoc_insertion_point(module_scope)
