#!/usr/bin/env python3
"""
Build script for Cloudflare Workers deployment.

This script reads all markdown documentation from the single source of truth
(finlab-plugin/skills/finlab/*.md) and generates a main.py file with the
documentation embedded as Python strings.

Run this before deploying to Cloudflare Workers.
"""

import json
from pathlib import Path

# Paths
SCRIPT_DIR = Path(__file__).parent
DOCS_DIR = SCRIPT_DIR.parent / "finlab-plugin" / "skills" / "finlab"
OUTPUT_FILE = SCRIPT_DIR / "src" / "main.py"

# Files to exclude
EXCLUDED_FILES = {"SKILL.md", "README.md"}


def load_documents() -> dict[str, str]:
    """Load all documentation files into a dictionary."""
    docs = {}
    for md_file in sorted(DOCS_DIR.glob("*.md")):
        if md_file.name in EXCLUDED_FILES:
            continue
        docs[md_file.stem] = md_file.read_text(encoding="utf-8")
        print(f"  Loaded: {md_file.name} ({len(docs[md_file.stem])} chars)")
    return docs


def generate_main_py(docs: dict[str, str]) -> str:
    """Generate the main.py file content with embedded documentation."""
    docs_json = json.dumps(docs, ensure_ascii=False, indent=2)

    return f'''"""
FinLab MCP Server for Cloudflare Workers

Auto-generated by build.py - DO NOT EDIT MANUALLY
Documentation is embedded from finlab-plugin/skills/finlab/*.md
"""

from mcp.server.fastmcp import FastMCP

mcp = FastMCP("finlab-docs")

# Embedded documentation (auto-generated from finlab-plugin/skills/finlab/*.md)
DOCS: dict[str, str] = {docs_json}


def search_in_docs(query: str) -> list[dict]:
    """Search for a keyword in all documentation."""
    results = []
    query_lower = query.lower()

    for name, content in DOCS.items():
        if query_lower not in content.lower():
            continue

        lines = content.split("\\n")
        for i, line in enumerate(lines):
            if query_lower in line.lower():
                start = max(0, i - 2)
                end = min(len(lines), i + 6)
                context = "\\n".join(lines[start:end])
                results.append({{
                    "file": name,
                    "line": i + 1,
                    "match": context
                }})

    return results[:10]


@mcp.tool()
def list_documents() -> str:
    """List all available FinLab documentation files."""
    docs_list = []
    for name, content in sorted(DOCS.items()):
        first_line = ""
        for line in content.split("\\n"):
            if line.strip():
                first_line = line.strip("# ").strip()
                break
        docs_list.append(f"- **{{name}}**: {{first_line}}")

    return "## Available FinLab Documents\\n\\n" + "\\n".join(docs_list)


@mcp.tool()
def get_document(doc_name: str) -> str:
    """Get the full content of a FinLab documentation file.

    Args:
        doc_name: Name of the document (without .md extension).
                  Available: data-reference, backtesting-reference, dataframe-reference,
                  factor-examples, factor-analysis-reference, trading-reference,
                  best-practices, machine-learning-reference
    """
    if doc_name in DOCS:
        return DOCS[doc_name]

    available = ", ".join(sorted(DOCS.keys()))
    return f"Document '{{doc_name}}' not found.\\n\\nAvailable documents: {{available}}"


@mcp.tool()
def search_finlab_docs(query: str) -> str:
    """Search for a keyword or phrase in all FinLab documentation.

    Args:
        query: The search term to look for (case-insensitive)
    """
    results = search_in_docs(query)

    if not results:
        return f"No results found for '{{query}}'"

    output = f"## Search Results: {{query}}\\n\\n"
    for r in results:
        output += f"### {{r['file']}} (line {{r['line']}})\\n"
        output += f"```\\n{{r['match']}}\\n```\\n\\n"

    return output


@mcp.tool()
def get_factor_examples(factor_type: str = "all") -> str:
    """Get factor/strategy examples from the documentation.

    Args:
        factor_type: Type of factor to filter by. Options:
                     - "all": All examples
                     - "value": Value investing factors
                     - "momentum": Price momentum strategies
                     - "technical": Technical analysis indicators
                     - "quality": Quality factors
                     - "ml": Machine learning strategies
    """
    if "factor-examples" not in DOCS:
        return "factor-examples not found"

    content = DOCS["factor-examples"]

    if factor_type == "all":
        return content

    factor_type_lower = factor_type.lower()
    sections = content.split("\\n## ")

    matching_sections = []
    for section in sections:
        if factor_type_lower in section.lower():
            matching_sections.append("## " + section)

    if not matching_sections:
        return f"No examples found for factor type '{{factor_type}}'. Try: value, momentum, technical, quality, ml"

    return "\\n\\n".join(matching_sections)


# Create the Streamable HTTP app for Cloudflare Workers
app = mcp.streamable_http_app()
'''


def main():
    print("Building FinLab MCP Server for Cloudflare Workers...")
    print(f"Reading docs from: {DOCS_DIR}")

    if not DOCS_DIR.exists():
        print(f"ERROR: Documentation directory not found: {DOCS_DIR}")
        return 1

    docs = load_documents()
    print(f"Loaded {len(docs)} documents")

    main_py_content = generate_main_py(docs)

    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_FILE.write_text(main_py_content, encoding="utf-8")
    print(f"Generated: {OUTPUT_FILE}")

    print("Build complete!")
    return 0


if __name__ == "__main__":
    exit(main())
