// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type ebpfGoRuntimeEventT struct {
	_               structs.HostLayout
	Timestamp       uint64
	EventType       uint32
	ProbeDurationNs uint32
	Goroutine       uint32
	ParentGoroutine uint32
	Attributes      [5]uint64
}

// loadEbpf returns the embedded CollectionSpec for ebpf.
func loadEbpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_EbpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load ebpf: %w", err)
	}

	return spec, err
}

// loadEbpfObjects loads ebpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*ebpfObjects
//	*ebpfPrograms
//	*ebpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadEbpfObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadEbpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// ebpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ebpfSpecs struct {
	ebpfProgramSpecs
	ebpfMapSpecs
	ebpfVariableSpecs
}

// ebpfProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ebpfProgramSpecs struct {
	UprobeCasgstatus *ebpf.ProgramSpec `ebpf:"uprobe_casgstatus"`
	UprobeGoexit1    *ebpf.ProgramSpec `ebpf:"uprobe_goexit1"`
	UprobeMakemap    *ebpf.ProgramSpec `ebpf:"uprobe_makemap"`
	UprobeMakeslice  *ebpf.ProgramSpec `ebpf:"uprobe_makeslice"`
	UprobeNewobject  *ebpf.ProgramSpec `ebpf:"uprobe_newobject"`
	UprobeNewproc1   *ebpf.ProgramSpec `ebpf:"uprobe_newproc1"`
}

// ebpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ebpfMapSpecs struct {
	Events               *ebpf.MapSpec `ebpf:"events"`
	GoroutinesInCreation *ebpf.MapSpec `ebpf:"goroutines_in_creation"`
	GoroutinesInExit     *ebpf.MapSpec `ebpf:"goroutines_in_exit"`
	SamplingRates        *ebpf.MapSpec `ebpf:"sampling_rates"`
}

// ebpfVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ebpfVariableSpecs struct {
	UnusedGoRuntimeEventT *ebpf.VariableSpec `ebpf:"unused_go_runtime_event_t"`
}

// ebpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadEbpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type ebpfObjects struct {
	ebpfPrograms
	ebpfMaps
	ebpfVariables
}

func (o *ebpfObjects) Close() error {
	return _EbpfClose(
		&o.ebpfPrograms,
		&o.ebpfMaps,
	)
}

// ebpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadEbpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type ebpfMaps struct {
	Events               *ebpf.Map `ebpf:"events"`
	GoroutinesInCreation *ebpf.Map `ebpf:"goroutines_in_creation"`
	GoroutinesInExit     *ebpf.Map `ebpf:"goroutines_in_exit"`
	SamplingRates        *ebpf.Map `ebpf:"sampling_rates"`
}

func (m *ebpfMaps) Close() error {
	return _EbpfClose(
		m.Events,
		m.GoroutinesInCreation,
		m.GoroutinesInExit,
		m.SamplingRates,
	)
}

// ebpfVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadEbpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type ebpfVariables struct {
	UnusedGoRuntimeEventT *ebpf.Variable `ebpf:"unused_go_runtime_event_t"`
}

// ebpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadEbpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type ebpfPrograms struct {
	UprobeCasgstatus *ebpf.Program `ebpf:"uprobe_casgstatus"`
	UprobeGoexit1    *ebpf.Program `ebpf:"uprobe_goexit1"`
	UprobeMakemap    *ebpf.Program `ebpf:"uprobe_makemap"`
	UprobeMakeslice  *ebpf.Program `ebpf:"uprobe_makeslice"`
	UprobeNewobject  *ebpf.Program `ebpf:"uprobe_newobject"`
	UprobeNewproc1   *ebpf.Program `ebpf:"uprobe_newproc1"`
}

func (p *ebpfPrograms) Close() error {
	return _EbpfClose(
		p.UprobeCasgstatus,
		p.UprobeGoexit1,
		p.UprobeMakemap,
		p.UprobeMakeslice,
		p.UprobeNewobject,
		p.UprobeNewproc1,
	)
}

func _EbpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed ebpf_x86_bpfel.o
var _EbpfBytes []byte
