up:
	docker-compose -f docker-compose-final.yml up -d

# Stop and remove the containers

down:
	docker-compose -f docker-compose-final.yml down

clickhouse:
	docker exec -it clickhouse-server /bin/bash

python:
	docker exec -it python-client /bin/bash
