// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v6.30.2
// source: api.proto

package apipb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	AccountBalanceService_BatchSubmitBalanceChanges_FullMethodName = "/apipb.AccountBalanceService/BatchSubmitBalanceChanges"
)

// AccountBalanceServiceClient is the client API for AccountBalanceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AccountBalanceServiceClient interface {
	BatchSubmitBalanceChanges(ctx context.Context, in *BatchSubmitBalanceChangesRequest, opts ...grpc.CallOption) (*BatchSubmitBalanceChangesResponse, error)
}

type accountBalanceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAccountBalanceServiceClient(cc grpc.ClientConnInterface) AccountBalanceServiceClient {
	return &accountBalanceServiceClient{cc}
}

func (c *accountBalanceServiceClient) BatchSubmitBalanceChanges(ctx context.Context, in *BatchSubmitBalanceChangesRequest, opts ...grpc.CallOption) (*BatchSubmitBalanceChangesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchSubmitBalanceChangesResponse)
	err := c.cc.Invoke(ctx, AccountBalanceService_BatchSubmitBalanceChanges_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountBalanceServiceServer is the server API for AccountBalanceService service.
// All implementations must embed UnimplementedAccountBalanceServiceServer
// for forward compatibility
type AccountBalanceServiceServer interface {
	BatchSubmitBalanceChanges(context.Context, *BatchSubmitBalanceChangesRequest) (*BatchSubmitBalanceChangesResponse, error)
	mustEmbedUnimplementedAccountBalanceServiceServer()
}

// UnimplementedAccountBalanceServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAccountBalanceServiceServer struct {
}

func (UnimplementedAccountBalanceServiceServer) BatchSubmitBalanceChanges(context.Context, *BatchSubmitBalanceChangesRequest) (*BatchSubmitBalanceChangesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchSubmitBalanceChanges not implemented")
}
func (UnimplementedAccountBalanceServiceServer) mustEmbedUnimplementedAccountBalanceServiceServer() {}

// UnsafeAccountBalanceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AccountBalanceServiceServer will
// result in compilation errors.
type UnsafeAccountBalanceServiceServer interface {
	mustEmbedUnimplementedAccountBalanceServiceServer()
}

func RegisterAccountBalanceServiceServer(s grpc.ServiceRegistrar, srv AccountBalanceServiceServer) {
	s.RegisterService(&AccountBalanceService_ServiceDesc, srv)
}

func _AccountBalanceService_BatchSubmitBalanceChanges_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchSubmitBalanceChangesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountBalanceServiceServer).BatchSubmitBalanceChanges(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountBalanceService_BatchSubmitBalanceChanges_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountBalanceServiceServer).BatchSubmitBalanceChanges(ctx, req.(*BatchSubmitBalanceChangesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AccountBalanceService_ServiceDesc is the grpc.ServiceDesc for AccountBalanceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AccountBalanceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "apipb.AccountBalanceService",
	HandlerType: (*AccountBalanceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BatchSubmitBalanceChanges",
			Handler:    _AccountBalanceService_BatchSubmitBalanceChanges_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
