# 使用 Python 3.9.5 slim-buster 映像
FROM python:3.9.5-slim-buster

# 設置工作目錄為 /app
WORKDIR /app

# 更新 apt-get 和安裝 vim
RUN apt-get update && \
    apt-get install -y vim && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# 複製依賴文件
COPY requirements.txt requirements.txt

# 安裝 Python 依賴
RUN pip3 install -r requirements.txt

# 複製應用所需的代碼文件
COPY model.py main.py config.py config.json ./

# 設置環境變量，標識運行在 Docker 中
ENV AM_I_IN_DOCKER Yes

# 設置容器啟動命令
CMD ["python3", "main.py"]

